### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by yyjdelete** [UudrSgMEZ/V2RayGCon#5] opened 2019-08-12 02:09 UTC
Version: 1.2.2
`AutocompleteMenu` should be disposed when (Lua/Json)Editor is closed, or Scintilla is disposed.

```cs
System.AccessViolationException
   at ScintillaNET.Scintilla.DirectMessage(IntPtr, Int32, IntPtr, IntPtr)
   at ScintillaNET.Scintilla.get_ReadOnly()
   at ScintillaWrapper.get_Readonly()
   at AutocompleteMenuNS.AutocompleteMenu.ShowAutocomplete(Boolean)
   at AutocompleteMenuNS.AutocompleteMenu.timer_Tick(System.Object, System.EventArgs)
   at System.Windows.Forms.Timer.OnTick(System.EventArgs)
   at System.Windows.Forms.Timer+TimerNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at V2RayGCon.Program.Main()
```

**Comment by UudrSgMEZ** [comment] 2019-08-12 15:16
I could not reproduce this bug. And after a little digging, I found AutocompleteMenu will dispose itself while form closing. Calling dispose method manually can cause problems.

Frankly, I am not sure how to fix this.
Any help would be appreciated.

**Closed** 2019-10-05 05:08 UTC
Labels: help wanted, nobot
